= Source repository usage
Wanjee
:published_at: 2014-05-06
:hp-tags: Quality,Drupal,Symfony2

Topic of the day: Source repository usage


== What to do ?

* Create a "www" folder in trunk root in which your project files will be located
* In "www" you should have nothing else than your project files and code (no db backup, no tmp folder,…)
* Custom code is separated from contrib one
** Drupal: modules/custom vs modules/contrib
*** sites/all/modules/contrib/...
*** sites/all/modules/custom/... (even if we don't use any contrib module)
*** sites/all/themes/contrib/...
*** sites/all/themes/custom/... (even if we don't use any contrib theme)
*** features are custom modules and should therefore also be located in /custom/ (NOT in features or whatever)
** Symfony: src vs vendors
*** Add all files that should not be versionned to the ignore list at the very beginning of the project.  See .gitignore examples (ignored files are also valid for SVN)
* All uppercased txt files from Drupal should not be deployed (CHANGELOG.txt, INSTALL.txt, INSTALL.mysql.txt, INSTALL.pgsql.txt, INSTALL.sqlite.txt, LICENSE.txt, MAINTAINERS.txt, UPGRADE.txt) Ignore them. 
* Do not commit project files from your IDE or hidden files from your OS.  Ignore them as well.
* robots.txt and .htaccess files must be on SVN and deployed.
* install.php file is also not supposed to b deployed.  Ignore it.  Get it when needed and remove it afterwards.
* No backup files on repository ("backup", "old", "file_",…)
* Properly manage environment configuration.
** Drupal: site/default/settings.php file should be ignored. Each environment settings file is defined in a the corresponding sub folder (i.e. sites/my_domain.com/settings.php) 
** Symfony: define settings in parameters.yml.dist, never commit parameters.yml file that will be generated by composer.
* Do not version big binary files (>2MB).  This bloats your repository and makes everything slow. Add them to ignore list and upload them via FTP.

 
== Why it's important ?

* Source repositories will be used for automated deployments.  We want deployments to be as fast as possible so the lighter the code base is the faster our sites will deploy.  
* We cannot deploy complete backup file of DB content to production.
* Backups on VCS has security implications.
* Other developers do not want a checkout to take ages.  If you want media files from production get them via FTP.
* A common structure is easier to use with scripts (code quality review, deploy,…) and easier to understand for developers.
* Source repository tools are meant to keep history of files so keeping old version of a file is a non sense and also a possible security issue.

