= Comment Driven Development
:name: Wanjee
:published_at: 2015-03-09
:hp-tags: Quality,Drupal,Symfony2


== How does it work ?

=== 1. When implementing a new function start by a description of its behavior in plain language.
----
/**
 * Get list of jobs
 *
 * Fetch all published jobs
 * ordered by their publication date, most recent are listed first.
 * You can alter this behavior by passing options
 *
 */
function getJobList() {
}
----
=== 2. Also add description of parameters, if any, and returned value.
----
/**
 * Get list of jobs
 *
 * Fetch all published jobs
 * ordered by their publication date, most recent are listed first
 * You can alter this behavior by passing specific filters as arguments.
 * A filter is a job field name having a given value
 * i.e. $filters = array('locale' => 'AR')
 *
 * @param array $filters List of arguments to filter the list on.
 * @return array Filtered and ordered list of jobs.
 */
function getJobList($filters = array()) {
}
----
=== 3. Then describe the internal logic of your function, as plain language again, in comments
----
/**
 * Get list of jobs
 *
 * Fetch all published jobs
 * ordered by their publication date, most recent are listed first
 * You can alter this behavior by passing specific filters as arguments.
 * A filter is a job field name having a given value
 * i.e. $filters = array('locale' => 'AR')
 *
 * @param array $filters List of arguments to filter the list on.
 * @return array Filtered and ordered list of jobs.
 */
function getJobList($filters = array) {
    // Ensure filters are valid
  
    // Ensure default filters are always set
 
    // Build the query
 
    // Loop through results
 
    // Return prepared jobs
}
----
=== 4. Last step is filling the blanks with your code. 
=== 5. Repeat for next function

 
== Why it's important ?

* Comments are important for maintenance of applications, for your colleagues but also for you.
* Describing your application logic is more natural in plain language than in PHP, you don't have to take care of the syntax of exact function to call.  It's therefore more fluent.
* Once comments are written you get the whole picture of what you want to achieve, you can now focus on how to properly write the corresponding PHP/JS/whatever code
* Once code is written you don't have to comment it, it's already done ! (You should still consider a proof reading of all comments)